name: Dodaj
description: 🆕 Zaproponuj coś, co można dodać do listy
title: '[DODAJ] <title>'
labels: ['Suggested Addition', 'Awaiting Review']
assignees:
  - kporembinski
body:
  # Location
  - type: input
    id: location
    attributes:
      label: Lokalizacja
      description: >-
        Wskaż, w której sekcji (i ewentualnie podsekcji) należy dokonać uzupełnienia.
      placeholder:
    validations:
      required: true

  # Addition Info
  - type: textarea
    id: addition
    attributes:
      label: Dodaj
      description: >-
        Proszę opisać, co należy dodać. W stosownych przypadkach proszę podać linki do wiarygodnych źródeł potwierdzających wszelkie informacje.
      placeholder: 
    validations:
      required: true

  # Can user submit PR
  - type: dropdown
    id: canImplement
    attributes:
      label: Czy chcesz przesłać Pull Request?
      description: Czy jesteś gotów zgłosić pull request dotyczący tego dodatku?
      options:
        - 'Nie'
        - 'Może'
        - 'Tak'
    validations:
      required: false

  # Confirmation checkboxes
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Proszę zaznaczyć odpowiednie pola
      options:
        - label: Zgodnie z moją najlepszą wiedzą, podane przeze mnie informacje są prawidłowe.
          required: true
        - label: Sprawdziłem, że podobne zgłoszenie nie zostało wcześniej otwarte.
          required: true
        - label: Zgadzam się z zasadami repozytorium [Kodeks postępowania](https://github.com/kporembinski/zabezpieczsie.pl/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
